"""empty message

Revision ID: 1a768f797a3
Revises: 315f4c21e86
Create Date: 2015-07-05 00:25:23.420487

"""

# revision identifiers, used by Alembic.
revision = '1a768f797a3'
down_revision = '315f4c21e86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicelogs', sa.Column('device_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devicelogs', 'device_id')
    ### end Alembic commands ###
