"""empty message

Revision ID: 315f4c21e86
Revises: None
Create Date: 2015-07-04 23:14:24.302205

"""

# revision identifiers, used by Alembic.
revision = '315f4c21e86'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicelogs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devicelogs')
    ### end Alembic commands ###
