"""empty message

Revision ID: 4be24df723
Revises: 1a768f797a3
Create Date: 2015-07-05 01:06:16.094791

"""

# revision identifiers, used by Alembic.
revision = '4be24df723'
down_revision = '1a768f797a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
